[heroku] Fix broken deployment due to src layout
Heroku can no longer import the application package from the current working
directory, because it is now located under a `src` directory. Ensure the package
gets installed on deployment by adding it to the requirements file.

  Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
  worker.init_process()
  File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
  self.load_wsgi()
  File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
  self.wsgi = self.app.wsgi()
  File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
  self.callable = self.load()
  File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
  return self.load_wsgiapp()
  File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
  return util.import_app(self.app_uri)
  File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
  __import__(module)
  File "/app/wsgi.py", line 1, in <module>
  import muckr.app
  ModuleNotFoundError: No module named 'muckr'